name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova Project
        shell: bash
        run: |
          cordova create myApp com.example.app NBUC

          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='myApp' \
            ./ myApp/www/

          cd myApp
          cordova platform add android

      - name: Build APK
        working-directory: myApp
        run: |
          cordova build android --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: myApp/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
